# Generated by Django 3.2.6 on 2021-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('rated', models.CharField(max_length=200)),
                ('released', models.CharField(max_length=200)),
                ('runtime', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('awards', models.TextField(null=True)),
                ('poster', models.TextField(null=True)),
                ('ratings', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('dvd', models.TextField(null=True)),
                ('box_office', models.TextField(null=True)),
                ('production', models.TextField(null=True)),
            ],
        ),
    ]
