# Generated by Django 3.2.6 on 2021-08-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ratings',
            new_name='imdbRating',
        ),
    ]
